version: "3"

services:
  postgres:
    image: envkeeper/postgres-image:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5050:5432
    networks:
      default:
        aliases:
          - postgres

volumes:
  postgres:
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 13.14.15.16/24
          gateway: 13.14.15.1

